//! Text -> node golden cases. Extend with every string fixed from the `unmapped` QA report.
use causal_chain::{Dict, Source};

const CASES: &[(Source, &str, &str)] = &[
    (Source::Occ08, "Loss of engine power (total)", "crit.power_loss.total"),
    (Source::Occ08, "Loss of engine power (partial)", "crit.power_loss.partial"),
    (Source::Occ08, "Off-field or emergency landing", "end.forced_landing"),
    (Source::Occ08, "Collision with terr/obj (non-CFIT)", "end.collision"),
    (Source::Occ08, "Controlled flight into terr/obj", "end.cfit"),
    (Source::Occ08, "Aerodynamic stall/spin", "crit.stall_spin"),
    (Source::Occ08, "Loss of control in flight", "crit.loc_inflight"),
    (Source::Occ08, "Loss of control on ground", "crit.loc_ground"),
    (Source::Occ08, "VFR encounter with IMC", "crit.vfr_into_imc"),
    (Source::Occ08, "Hard landing", "end.hard_landing"),
    (Source::Occ08, "Landing gear not configured", "end.gear_up"),
    (Source::Occ08, "Midair collision", "end.midair"),
    (Source::Occ08, "Fuel exhaustion", "mech.fuel.exhaustion"),
    (Source::Occ08, "Unknown or undetermined", "und.not_determined"),
    (Source::Find08, "Aircraft-Fluids/misc hardware-Fluids-Fuel-Fuel starvation", "mech.fuel.starvation"),
    (Source::Find08, "Aircraft-Fluids/misc hardware-Fluids-Fuel-Fuel exhaustion", "mech.fuel.exhaustion"),
    (Source::Find08, "Aircraft-Aircraft power plant-Engine (reciprocating)-Induction system-Carburetor icing", "mech.induction_icing"),
    (Source::Find08, "Aircraft-Aircraft power plant-Engine (reciprocating)-Recip engine power section-Connecting rod-Fatigue/wear/corrosion", "mech.engine.internal"),
    (Source::Find08, "Aircraft-Aircraft power plant-Engine (reciprocating)-(general)-Unknown/Not determined", "mech.engine.undetermined"),
    (Source::Find08, "Aircraft-Aircraft oper/perf/capability-Performance/control parameters-Angle of attack-Capability exceeded", "mech.aero.aoa_exceeded"),
    (Source::Find08, "Aircraft-Aircraft oper/perf/capability-Performance/control parameters-Climb capability-Not attained/maintained", "mech.aero.performance"),
    (Source::Find08, "Personnel issues-Psychological-Perception/orientation/illusion-Spatial disorientation-Pilot", "mech.spatial_disorientation"),
    (Source::Find08, "Personnel issues-Task performance-Use of equip/info-Fuel tank selector position-Pilot", "act.pilot.fuel_mgmt"),
    (Source::Find08, "Personnel issues-Task performance-Planning/preparation-Fuel planning-Pilot", "act.pilot.fuel_mgmt"),
    (Source::Find08, "Personnel issues-Task performance-Use of equip/info-Carburetor heat-Pilot", "act.pilot.carb_heat"),
    (Source::Find08, "Personnel issues-Aircraft control-Airspeed-Not attained/maintained-Pilot", "act.pilot.airspeed"),
    (Source::Find08, "Personnel issues-Aircraft control-Directional control-Pilot", "act.pilot.directional_control"),
    (Source::Find08, "Personnel issues-Task performance-Use of equip/info-Crosswind compensation-Pilot", "act.pilot.wind_comp"),
    (Source::Find08, "Personnel issues-Task performance-Use of equip/info-Landing flare-Pilot", "act.pilot.flare_landing"),
    (Source::Find08, "Personnel issues-Task performance-Use of equip/info-Landing gear extension-Pilot", "act.pilot.gear"),
    (Source::Find08, "Personnel issues-Task performance-Use of equip/info-Instrument approach procedure-Pilot", "act.pilot.ifr_procedure"),
    (Source::Find08, "Personnel issues-Action/decision-Action-Low altitude flight/maneuver-Pilot", "act.pilot.low_flight"),
    (Source::Find08, "Personnel issues-Task performance-Monitoring environment-Visual lookout-Pilot", "act.pilot.lookout"),
    (Source::Find08, "Personnel issues-Action/decision-Info processing/decision-Decision making/judgment-Pilot", "act.pilot.decision"),
    (Source::Find08, "Personnel issues-Task performance-Planning/preparation-Weather planning-Pilot", "act.pilot.wx_planning"),
    (Source::Find08, "Personnel issues-Task performance-Planning/preparation-Performance calculations-Pilot", "act.pilot.performance_planning"),
    (Source::Find08, "Personnel issues-Task performance-Use of equip/info-Checklist-Pilot", "act.pilot.checklist"),
    (Source::Find08, "Personnel issues-Task performance-Inspection-Maintenance personnel", "act.maint.improper"),
    (Source::Find08, "Personnel issues-Aircraft control-Aircraft control-Pilot", "act.pilot.aircraft_control"),
    (Source::Find08, "Personnel issues-Physical-Alcohol/drug-Impairment(drug/alcohol)-Pilot", "latent.pilot.impairment"),
    (Source::Find08, "Personnel issues-Experience/knowledge-Total instrument experience-Pilot", "latent.pilot.experience"),
    (Source::Find08, "Not determined-Not determined-(general)-(general)-Unknown/Not determined", "und.not_determined"),
    (Source::Find08, "Environmental issues-Conditions/weather/phenomena-Ceiling/visibility/precip-Low ceiling", "env.wx.imc"),
    (Source::Find08, "Environmental issues-Conditions/weather/phenomena-Conducive to carburetor icing-Effect on equipment", "env.wx.icing"),
    (Source::Find08, "Environmental issues-Conditions/weather/phenomena-Wind-Gusts-Effect on operation", "env.wx.wind"),
    (Source::Find08, "Environmental issues-Conditions/weather/phenomena-High density altitude-Effect on operation", "env.wx.density_altitude"),
    (Source::Find08, "Environmental issues-Physical environment-Object/animal/substance-Other aircraft-Effect on operation", "env.traffic"),
    (Source::Find08, "Environmental issues-Physical environment-Object/animal/substance-Bird-Effect on equipment", "env.wildlife"),
    (Source::Find08, "Environmental issues-Physical environment-Object/animal/substance-Wire-Effect on operation", "env.obstacle"),
    (Source::Find08, "Environmental issues-Physical environment-Terrain-Trees-Effect on operation", "env.terrain"),
    (Source::OccPre08, "LOSS OF ENGINE POWER(TOTAL) - NONMECHANICAL", "crit.power_loss.total"),
    (Source::OccPre08, "LOSS OF ENGINE POWER(PARTIAL) - MECH FAILURE/MALF", "crit.power_loss.partial"),
    (Source::OccPre08, "FORCED LANDING", "end.forced_landing"),
    (Source::OccPre08, "IN FLIGHT COLLISION WITH TERRAIN/WATER", "end.collision"),
    (Source::OccPre08, "LOSS OF CONTROL - IN FLIGHT", "crit.loc_inflight"),
    (Source::OccPre08, "LOSS OF CONTROL - ON GROUND/WATER", "crit.loc_ground"),
    (Source::OccPre08, "STALL/SPIN", "crit.stall_spin"),
    (Source::OccPre08, "WHEELS UP LANDING", "end.gear_up"),
    (Source::OccPre08, "NOSE OVER", "end.nose_over"),
    (Source::FindPre08, "FLUID,FUEL - STARVATION", "mech.fuel.starvation"),
    (Source::FindPre08, "FLUID,FUEL - EXHAUSTION", "mech.fuel.exhaustion"),
    (Source::FindPre08, "FUEL TANK SELECTOR POSITION - IMPROPER - PILOT IN COMMAND", "act.pilot.fuel_mgmt"),
    (Source::FindPre08, "FUEL SUPPLY - INADEQUATE - PILOT IN COMMAND", "act.pilot.fuel_mgmt"),
    (Source::FindPre08, "CARBURETOR ICE", "mech.induction_icing"),
    (Source::FindPre08, "CARBURETOR HEAT - NOT USED - PILOT IN COMMAND", "act.pilot.carb_heat"),
    (Source::FindPre08, "ENGINE ASSEMBLY,CONNECTING ROD - FATIGUE", "mech.engine.internal"),
    (Source::FindPre08, "STALL - INADVERTENT - PILOT IN COMMAND", "mech.aero.aoa_exceeded"),
    (Source::FindPre08, "AIRSPEED - NOT MAINTAINED - PILOT IN COMMAND", "act.pilot.airspeed"),
    (Source::FindPre08, "SPATIAL DISORIENTATION - PILOT IN COMMAND", "mech.spatial_disorientation"),
    (Source::FindPre08, "VFR FLIGHT INTO IMC - CONTINUED - PILOT IN COMMAND", "act.pilot.decision"),
    (Source::FindPre08, "DIRECTIONAL CONTROL - NOT MAINTAINED - PILOT IN COMMAND", "act.pilot.directional_control"),
    (Source::FindPre08, "COMPENSATION FOR WIND CONDITIONS - INADEQUATE - PILOT IN COMMAND", "act.pilot.wind_comp"),
    (Source::FindPre08, "FLARE - IMPROPER - PILOT IN COMMAND", "act.pilot.flare_landing"),
    (Source::FindPre08, "LANDING GEAR EXTENSION - NOT PERFORMED - PILOT IN COMMAND", "act.pilot.gear"),
    (Source::FindPre08, "VISUAL LOOKOUT - INADEQUATE - PILOT IN COMMAND", "act.pilot.lookout"),
    (Source::FindPre08, "MAINTENANCE,INSPECTION - INADEQUATE - COMPANY MAINTENANCE PERSONNEL", "act.maint.improper"),
    (Source::FindPre08, "ALCOHOL - IMPAIRED - PILOT IN COMMAND", "latent.pilot.impairment"),
    (Source::FindPre08, "REASON FOR OCCURRENCE UNDETERMINED", "und.not_determined"),
    (Source::FindPre08, "WEATHER CONDITION - LOW CEILING", "env.wx.imc"),
    (Source::FindPre08, "WEATHER CONDITION - GUSTS", "env.wx.wind"),
    (Source::FindPre08, "WEATHER CONDITION - CARBURETOR ICING CONDITIONS", "env.wx.icing"),
    (Source::FindPre08, "TERRAIN CONDITION - TREES", "env.terrain"),
    (Source::FindPre08, "LIGHT CONDITION - DARK NIGHT", "env.light.dark"),
    (Source::FindPre08, "LOW ALTITUDE FLIGHT/MANEUVER - PILOT IN COMMAND", "act.pilot.low_flight"),
];

#[test]
fn text_maps_to_expected_node() {
    let d = Dict::from_toml(include_str!("../../../config/causal_nodes.toml")).unwrap();
    let mut bad = Vec::new();
    for (src, text, want) in CASES {
        let got = d.map(*src, text).map(|i| d.nodes[i].id.as_str()).unwrap_or("(unmapped)");
        if got != *want {
            bad.push(format!("{src:?} {text:?}: got {got}, want {want}"));
        }
    }
    assert!(bad.is_empty(), "\n{}", bad.join("\n"));
}
