# (make_raw, model_raw, series_raw, homebuilt, expected_family, expected_variant)
# Synthetic cases written in the style of NTSB acft_make / acft_model strings.
# "" variant = family match with no variant. None family = expected no match (fallback).
CASES = [
    ("CESSNA", "172N", "", False, "cessna_172", "c172n"),
    ("Cessna", "172S", "", False, "cessna_172", "c172s"),
    ("CESSNA AIRCRAFT CO", "172 SKYHAWK", "", False, "cessna_172", ""),
    ("Cessna", "172", "S", False, "cessna_172", "c172s"),
    ("CESSNA", "172RG", "", False, "cessna_172", "c172rg"),
    ("REIMS", "F172M", "", False, "cessna_172", "c172_bm"),
    ("CESSNA", "R172K", "", False, "cessna_172", "r172"),
    ("Textron Aviation Inc", "172S", "", False, "cessna_172", "c172s"),
    ("CESSNA", "C-172P", "", False, "cessna_172", "c172pq"),
    ("CESSNA", "150M", "", False, "cessna_150_152", "c150"),
    ("CESSNA", "A152", "", False, "cessna_150_152", "aerobat"),
    ("CESSNA", "152", "", False, "cessna_150_152", "c152"),
    ("CESSNA", "182T", "", False, "cessna_182", "c182"),
    ("CESSNA", "T182T", "", False, "cessna_182", "t182"),
    ("CESSNA", "R182", "", False, "cessna_182", "c182rg"),
    ("CESSNA", "177RG", "", False, "cessna_177", "c177rg"),
    ("CESSNA", "177B", "", False, "cessna_177", "c177"),
    ("CESSNA", "180K", "", False, "cessna_180", ""),
    ("CESSNA", "A185F", "", False, "cessna_185", ""),
    ("CESSNA", "U206G", "", False, "cessna_206", "c206"),
    ("CESSNA", "T206H", "", False, "cessna_206", "c206"),
    ("CESSNA", "P210N", "", False, "cessna_210", "p210"),
    ("CESSNA", "T210L", "", False, "cessna_210", "t210"),
    ("CESSNA", "140", "", False, "cessna_120_140", "c140"),
    ("CESSNA", "170B", "", False, "cessna_170", ""),
    ("CESSNA", "310R", "", False, "cessna_310_320", "c310"),
    ("CESSNA", "340A", "", False, "cessna_335_340", ""),
    ("CESSNA", "421C", "", False, "cessna_414_421", "c421"),
    ("CESSNA", "414A", "", False, "cessna_414_421", "c414"),
    ("CESSNA", "337G", "", False, "cessna_336_337", "c337"),
    ("CESSNA", "208B", "", False, "cessna_208", "c208b"),
    ("CESSNA", "441", "", False, "cessna_425_441", "c441"),
    ("CESSNA", "525", "", False, "citation_cj", "cj1_m2"),
    ("CESSNA", "525C", "", False, "citation_cj", "cj4"),
    ("CESSNA", "560XL", "", False, "citation_excel", ""),
    ("CESSNA", "560", "", False, "citation_500_series", "c560"),
    ("CESSNA", "550", "", False, "citation_500_series", "c550_551"),
    ("CESSNA", "510", "", False, "citation_mustang", ""),
    ("CESSNA", "680A", "", False, "citation_680", "c680a"),
    ("Textron Aviation Inc", "700", "", False, "citation_700", ""),
    ("CESSNA", "750", "", False, "citation_750", ""),
    ("CESSNA", "188B", "", False, "cessna_188", ""),
    ("COLUMBIA AIRCRAFT MFG", "LC41-550FG", "", False, "cessna_corvalis", ""),
    ("CESSNA", "400", "", False, "cessna_corvalis", ""),
    ("PIPER", "PA-28-161", "", False, "piper_pa28", "warrior"),
    ("Piper", "PA28-181", "", False, "piper_pa28", "archer"),
    ("PIPER", "PA-28-140", "", False, "piper_pa28", "cherokee_140"),
    ("PIPER", "PA-28-180", "", False, "piper_pa28", "cherokee_150_180"),
    ("PIPER", "PA-28R-201", "", False, "piper_pa28", "arrow"),
    ("PIPER", "PA-28RT-201T", "", False, "piper_pa28", "arrow"),
    ("PIPER", "PA-28-236", "", False, "piper_pa28", "dakota_235"),
    ("PIPER", "PA-28", "161", False, "piper_pa28", "warrior"),
    ("NEW PIPER AIRCRAFT INC", "PA-32R-301T", "", False, "piper_pa32", "pa32r"),
    ("PIPER", "PA-32-300", "", False, "piper_pa32", "pa32_fixed"),
    ("PIPER", "PA-34-200T", "", False, "piper_pa34", ""),
    ("PIPER", "PA-44-180", "", False, "piper_pa44", ""),
    ("PIPER", "PA-18-150", "", False, "piper_pa18", ""),
    ("PIPER", "J3C-65", "", False, "piper_j_cub", "j3"),
    ("PIPER", "PA-22-108", "", False, "piper_pa20_22", "pa22_108"),
    ("PIPER", "PA-20", "", False, "piper_pa20_22", "pa20"),
    ("PIPER", "PA-24-250", "", False, "piper_pa24", ""),
    ("PIPER", "PA-23-250", "", False, "piper_pa23", "aztec"),
    ("PIPER", "PA-31-350", "", False, "piper_pa31", "chieftain"),
    ("PIPER", "PA-31T", "", False, "piper_pa31", "cheyenne"),
    ("PIPER", "PA-42-720", "", False, "piper_pa42", ""),
    ("PIPER", "PA-46-310P", "", False, "piper_pa46", "pa46_piston"),
    ("PIPER", "PA-46-500TP", "", False, "piper_pa46", "pa46_turbine"),
    ("PIPER", "PA46-600TP", "", False, "piper_pa46", "pa46_turbine"),
    ("PIPER", "PA-38-112", "", False, "piper_pa38", ""),
    ("PIPER", "PA-25-235", "", False, "piper_pa25", ""),
    ("PIPER", "PA-36-375", "", False, "piper_pa36", ""),
    ("PIPER", "PA-30", "", False, "piper_pa30_39", ""),
    ("PIPER", "PA-60-601P", "", False, "piper_aerostar", ""),
    ("TED SMITH AEROSTAR", "601P", "", False, "piper_aerostar", ""),
    ("BEECH", "A36", "", False, "beech_bonanza", "be36"),
    ("Beech", "V35B", "", False, "beech_bonanza", "be35"),
    ("BEECH", "F33A", "", False, "beech_bonanza", "be33"),
    ("BEECH", "35-C33A", "", False, "beech_bonanza", "be33"),
    ("Textron Aviation Inc", "G36", "", False, "beech_bonanza", "be36"),
    ("BEECH", "58", "", False, "beech_baron", "be58"),
    ("BEECH", "95-B55", "", False, "beech_baron", "be55"),
    ("BEECH", "E55", "", False, "beech_baron", "be55"),
    ("BEECH", "D95A", "", False, "beech_95", ""),
    ("BEECH", "76", "", False, "beech_76", ""),
    ("BEECH", "77", "", False, "beech_77", ""),
    ("BEECH", "C23", "", False, "beech_musketeer", "sundowner"),
    ("BEECH", "B24R", "", False, "beech_musketeer", "sierra"),
    ("BEECH", "C90A", "", False, "beech_king_air_90_100", "ka90"),
    ("BEECH", "65-A90", "", False, "beech_king_air_90_100", "ka90"),
    ("BEECH", "B100", "", False, "beech_king_air_90_100", "ka100"),
    ("BEECH", "B200", "", False, "beech_king_air_200_300", "ka200_250"),
    ("RAYTHEON AIRCRAFT COMPANY", "B300", "", False, "beech_king_air_200_300", "ka300_350"),
    ("Textron Aviation Inc", "350", "", False, "beech_king_air_200_300", "ka300_350"),
    ("BEECH", "1900D", "", False, "beech_1900", ""),
    ("BEECH", "C99", "", False, "beech_99", ""),
    ("BEECH", "D18S", "", False, "beech_18", ""),
    ("BEECH", "A45", "", False, "beech_t34", ""),
    ("BEECH", "400A", "", False, "beechjet_400", ""),
    ("HAWKER BEECHCRAFT CORP", "400XP", "", False, "beechjet_400", ""),
    ("RAYTHEON AIRCRAFT COMPANY", "HAWKER 800XP", "", False, "hawker_125", ""),
    ("BRITISH AEROSPACE", "BAE 125-800A", "", False, "hawker_125", ""),
    ("RAYTHEON", "390", "", False, "beech_premier", ""),
    ("BEECH", "2000", "", False, "beech_2000", ""),
    ("MOONEY", "M20J", "", False, "mooney_m20", "m20j"),
    ("MOONEY", "M20TN", "", False, "mooney_m20", "m20tn"),
    ("MOONEY", "M20C", "", False, "mooney_m20", "m20a_e"),
    ("MOONEY", "M10", "", False, "ercoupe", ""),
    ("CIRRUS DESIGN CORP", "SR22", "", False, "cirrus_sr", "sr22"),
    ("CIRRUS DESIGN CORP", "SR22T", "", False, "cirrus_sr", "sr22t"),
    ("Cirrus", "SR20", "", False, "cirrus_sr", "sr20"),
    ("CIRRUS", "SF50", "", False, "cirrus_sf50", ""),
    ("DIAMOND AIRCRAFT IND INC", "DA 40", "", False, "diamond_da40", ""),
    ("DIAMOND", "DA20-C1", "", False, "diamond_da20", ""),
    ("DIAMOND", "DA42", "", False, "diamond_da42", ""),
    ("GRUMMAN AMERICAN AVN. CORP.", "AA-5B", "", False, "grumman_aa5", "aa5b"),
    ("GRUMMAN", "AA-1B", "", False, "grumman_aa1", ""),
    ("TIGER AIRCRAFT LLC", "AG-5B", "", False, "grumman_aa5", "aa5b"),
    ("GULFSTREAM AMERICAN CORP", "GA-7", "", False, "grumman_ga7", ""),
    ("SOCATA", "TB 20", "", False, "socata_tb", "tb20_21"),
    ("SOCATA", "TBM 700", "", False, "daher_tbm", "tbm700"),
    ("DAHER", "TBM 940", "", False, "daher_tbm", "tbm9xx"),
    ("QUEST AIRCRAFT COMPANY LLC", "KODIAK 100", "", False, "quest_kodiak", ""),
    ("ROCKWELL INTERNATIONAL", "114", "", False, "commander_112_114", ""),
    ("ERCO", "415-C", "", False, "ercoupe", ""),
    ("LUSCOMBE", "8A", "", False, "luscombe_8", ""),
    ("AERONCA", "7AC", "", False, "aeronca_champ", "7ac"),
    ("AERONCA", "11AC", "", False, "aeronca_chief", ""),
    ("CHAMPION", "7ECA", "", False, "champion_citabria", ""),
    ("AMERICAN CHAMPION AIRCRAFT", "8KCAB", "", False, "champion_decathlon", ""),
    ("BELLANCA", "7GCBC", "", False, "champion_citabria", ""),
    ("BELLANCA", "17-30A", "", False, "bellanca_viking", "viking"),
    ("TAYLORCRAFT", "BC12-D", "", False, "taylorcraft", ""),
    ("TAYLOR", "J-2", "", False, "piper_j_cub", "j2_j4"),
    ("STINSON", "108-3", "", False, "stinson", "s108"),
    ("MAULE", "M-7-235C", "", False, "maule", "maule_m7_m9"),
    ("MAULE", "MXT-7-180", "", False, "maule", "maule_tricycle"),
    ("AVIAT AIRCRAFT INC", "A-1B", "", False, "aviat_husky", ""),
    ("AVIAT AIRCRAFT INC", "PITTS S-2B", "", False, "pitts", "s2"),
    ("SMITH JOHN", "PITTS S-1C", "", True, "pitts", "s1"),
    ("CUBCRAFTERS INC", "CC11-160", "", False, "cubcrafters", "cc11"),
    ("EXTRA FLUGZEUGPRODUKTIONS", "EA 300/L", "", False, "extra", "ea300_330"),
    ("FLIGHT DESIGN GMBH", "CTLS", "", False, "flight_design_ct", ""),
    ("TECNAM", "P2008", "", False, "tecnam", "p2008"),
    ("COSTRUZIONI AERONAUTICHE TECNAM", "P2006T", "", False, "tecnam", "p2006t"),
    ("CESSNA", "162", "", False, "cessna_162", ""),
    ("ICON AIRCRAFT INC", "A5", "", False, "icon_a5", ""),
    ("CZECH SPORT AIRCRAFT AS", "PS-28 CRUISER", "", False, "piper_ps28", ""),
    ("VANS", "RV-7A", "", True, "vans_rv", "rv7a"),
    ("VAN'S AIRCRAFT INC", "RV-12", "", False, "vans_rv", "rv12"),
    ("JONES ROBERT", "RV-6", "", True, "vans_rv", "rv6"),
    ("JONES ROBERT", "VANS RV-10", "", True, "vans_rv", "rv10"),
    ("JONES ROBERT", "RV-14A", "", True, "vans_rv", "rv14a"),
    ("WILLIAMS", "LANCAIR IV-P", "", True, "lancair", "lancair_iv"),
    ("LANCAIR", "LEGACY", "", True, "lancair", "lancair_legacy"),
    ("BROWN", "GLASAIR III", "", True, "glasair", "glasair_iii"),
    ("BROWN", "GLASTAR", "", True, "glasair", "glastar_sportsman"),
    ("SMITH", "KITFOX IV", "", True, "kitfox", ""),
    ("SMITH", "CH 750", "", True, "zenith", "zenith_stol"),
    ("SMITH", "ZODIAC CH 601XL", "", True, "zenith", "zenith_zodiac"),
    ("SMITH", "LONG-EZ", "", True, "canard_pusher", "longez"),
    ("SMITH", "VELOCITY XL", "", True, "canard_pusher", "velocity"),
    ("SMITH", "SONEX", "", True, "sonex", ""),
    ("SMITH", "S-6ES COYOTE II", "", True, "rans", ""),
    ("SMITH", "S-12XL", "", True, "rans", ""),
    ("SMITH", "BEARHAWK", "", True, "bearhawk", ""),
    ("SMITH", "PIETENPOL AIR CAMPER", "", True, "pietenpol", ""),
    ("SMITH", "RV-7A", "", False, None, None),
    ("SMITH", "HATZ CB-1", "", True, None, None),
    ("AIR TRACTOR INC", "AT-802A", "", False, "air_tractor", "at802"),
    ("AIR TRACTOR", "AT-502B", "", False, "air_tractor", "at50x"),
    ("AIR TRACTOR", "AT-301", "", False, "air_tractor", "at300_400p"),
    ("THRUSH AIRCRAFT INC", "S2R-T34", "", False, "thrush", "thrush_turbine"),
    ("AYRES", "S2R-R1340", "", False, "thrush", "thrush_piston"),
    ("GRUMMAN", "G-164B", "", False, "grumman_agcat", ""),
    ("SCHWEIZER", "G-164A", "", False, "grumman_agcat", ""),
    ("LAKE", "LA-4-200", "", False, "lake", "la4"),
    ("GRUMMAN", "G-21A", "", False, "grumman_amphibians", "g21"),
    ("GRUMMAN", "G-44", "", False, "grumman_amphibians", "g44"),
    ("REPUBLIC", "RC-3", "", False, "republic_seabee", ""),
    ("DEHAVILLAND", "DHC-2 MK. I", "", False, "dhc2_beaver", "dhc2"),
    ("DE HAVILLAND", "DHC-2 MK III", "", False, "dhc2_beaver", "dhc2_turbo"),
    ("VIKING AIR LTD", "DHC-6-400", "", False, "dhc6_twin_otter", ""),
    ("DEHAVILLAND", "DHC-3", "", False, "dhc3_otter", ""),
    ("BOMBARDIER INC", "DHC-8-402", "", False, "dhc8", "dhc8_400"),
    ("PILATUS AIRCRAFT LTD", "PC-12/47E", "", False, "pilatus_pc12", "pc12_ngx"),
    ("PILATUS", "PC-12/45", "", False, "pilatus_pc12", "pc12_legacy"),
    ("PILATUS", "PC-6/B2-H4", "", False, "pilatus_pc6", ""),
    ("PILATUS", "PC-24", "", False, "pilatus_pc24", ""),
    ("EPIC", "LT", "", True, "epic", ""),
    ("AERO COMMANDER", "500S", "", False, "aero_commander_piston", ""),
    ("ROCKWELL", "690B", "", False, "turbo_commander", ""),
    ("GULFSTREAM AMERICAN CORP", "695A", "", False, "turbo_commander", ""),
    ("MITSUBISHI", "MU-2B-60", "", False, "mitsubishi_mu2", "mu2_long"),
    ("MITSUBISHI", "MU-2B-25", "", False, "mitsubishi_mu2", "mu2_short"),
    ("PIAGGIO", "P-180", "", False, "piaggio_p180", ""),
    ("SWEARINGEN", "SA227-AC", "", False, "swearingen_metro", "metro_iii_23"),
    ("SWEARINGEN", "SA226-T", "", False, "swearingen_merlin", ""),
    ("FAIRCHILD", "SA227-DC", "", False, "swearingen_metro", "metro_iii_23"),
    ("BRITISH AEROSPACE", "JETSTREAM 3101", "", False, "jetstream", "j31_32"),
    ("BRITISH AEROSPACE", "BAE-146-200", "", False, "bae146_avro", ""),
    ("SAAB", "340B", "", False, "saab_340_2000", "saab340"),
    ("EMBRAER", "EMB-120ER", "", False, "embraer_120", ""),
    ("EMBRAER", "EMB-145LR", "", False, "embraer_erj145", "erj145"),
    ("EMBRAER", "ERJ 170-200 LR", "", False, "embraer_ejet", "e175"),
    ("EMBRAER", "ERJ 190-100 IGW", "", False, "embraer_ejet", "e190"),
    ("EMBRAER", "EMB-505", "", False, "embraer_phenom", "phenom300"),
    ("EMBRAER", "EMB-500", "", False, "embraer_phenom", "phenom100"),
    ("EMBRAER", "EMB-135BJ", "", False, "embraer_legacy_600", ""),
    ("ATR", "ATR 72-212A", "", False, "atr", "atr72"),
    ("ECLIPSE AVIATION CORP", "EA500", "", False, "eclipse", ""),
    ("HONDA AIRCRAFT CO LLC", "HA-420", "", False, "hondajet", ""),
    ("GATES LEARJET", "35A", "", False, "learjet", "lj30s"),
    ("LEARJET INC", "60", "", False, "learjet", "lj55_60"),
    ("BOMBARDIER INC", "LEARJET 45", "", False, "learjet", "lj40_45_70_75"),
    ("DASSAULT AVIATION", "FALCON 2000EX", "", False, "dassault_falcon", "f2000"),
    ("DASSAULT-BREGUET", "MYSTERE FALCON 900", "", False, "dassault_falcon", "f900"),
    ("DASSAULT", "FALCON 50", "", False, "dassault_falcon", "f50"),
    ("DASSAULT", "FAN JET FALCON", "", False, "dassault_falcon", "f20"),
    ("GULFSTREAM AEROSPACE", "G-IV", "", False, "gulfstream", "giv_g450"),
    ("GULFSTREAM", "GULFSTREAM IV", "", False, "gulfstream", "giv_g450"),
    ("GULFSTREAM AEROSPACE CORP", "GV-SP", "", False, "gulfstream", "gv_g550"),
    ("GULFSTREAM AEROSPACE CORP", "GVI", "", False, "gulfstream", "gvi_g650"),
    ("GULFSTREAM AEROSPACE CORP", "GVII-G500", "", False, "gulfstream", "gvii"),
    ("GRUMMAN", "G-1159A", "", False, "gulfstream", "g1159_gii_giii"),
    ("GRUMMAN", "G-159", "", False, "gulfstream_i", ""),
    ("ISRAEL AIRCRAFT INDUSTRIES", "1125 WESTWIND ASTRA", "", False, "gulfstream", "g100_g150"),
    ("ISRAEL AIRCRAFT INDUSTRIES", "1124A", "", False, "iai_westwind", ""),
    ("BOMBARDIER INC", "CL-600-2B16", "", False, "bombardier_challenger", "c604_650"),
    ("BOMBARDIER INC", "BD-100-1A10", "", False, "bombardier_challenger", "c300_350"),
    ("BOMBARDIER INC", "BD-700-1A10", "", False, "bombardier_challenger", "global"),
    ("BOMBARDIER INC", "CL-600-2B19", "", False, "bombardier_crj", "crj100_200"),
    ("BOMBARDIER INC", "CL-600-2D24", "", False, "bombardier_crj", "crj900"),
    ("BOMBARDIER INC", "CL-600-2C10", "", False, "bombardier_crj", "crj700"),
    ("BOEING", "737-7H4", "", False, "boeing_737", "b737_ng"),
    ("BOEING", "737-832", "", False, "boeing_737", "b737_ng"),
    ("BOEING", "737", "7H4", False, "boeing_737", "b737_ng"),
    ("BOEING", "737-8", "", False, "boeing_737", "b737_max"),
    ("BOEING", "737-9", "", False, "boeing_737", "b737_max"),
    ("BOEING", "737 MAX 8", "", False, "boeing_737", "b737_max"),
    ("BOEING", "737-924ER", "", False, "boeing_737", "b737_ng"),
    ("BOEING", "737-3H4", "", False, "boeing_737", "b737_classic"),
    ("BOEING", "737-2H4", "", False, "boeing_737", "b737_original"),
    ("BOEING", "757-232", "", False, "boeing_757", "b757_200"),
    ("BOEING", "767-332ER", "", False, "boeing_767", "b767_300"),
    ("BOEING", "777-28E", "", False, "boeing_777", "b777_200"),
    ("BOEING", "787-9", "", False, "boeing_787", "b787_9"),
    ("BOEING", "747-400", "", False, "boeing_747", "b747_400"),
    ("BOEING", "727-223", "", False, "boeing_727", "b727_200"),
    ("BOEING", "717-200", "", False, "boeing_717", ""),
    ("BOEING", "MD-11F", "", False, "douglas_dc10_md11", "md11"),
    ("MCDONNELL DOUGLAS", "DC-9-82", "", False, "douglas_dc9_md80_90", "md80"),
    ("MCDONNELL DOUGLAS", "MD-88", "", False, "douglas_dc9_md80_90", "md80"),
    ("DOUGLAS", "DC-9-31", "", False, "douglas_dc9_md80_90", "dc9"),
    ("MCDONNELL DOUGLAS", "DC-10-30F", "", False, "douglas_dc10_md11", "dc10"),
    ("DOUGLAS", "DC-3C", "", False, "douglas_dc3", "dc3"),
    ("DOUGLAS", "C-47A", "", False, "douglas_dc3", "dc3"),
    ("BASLER", "BT-67", "", False, "douglas_dc3", "bt67"),
    ("DOUGLAS", "DC-6B", "", False, "douglas_dc4_6_7", "dc6"),
    ("AIRBUS", "A320-214", "", False, "airbus_a320_family", "a320"),
    ("AIRBUS INDUSTRIE", "A321-231", "", False, "airbus_a320_family", "a321"),
    ("AIRBUS", "A330-243", "", False, "airbus_a330", ""),
    ("AIRBUS", "A300F4-605R", "", False, "airbus_a300_310", "a300"),
    ("AIRBUS CANADA LTD PTNRSP", "BD-500-1A10", "", False, "airbus_a220", ""),
    ("LOCKHEED", "L-382G", "", False, "lockheed_l382", ""),
    ("CONVAIR", "CV-580", "", False, "convair_580", ""),
    ("CONVAIR", "340", "", False, "convair_piston", ""),
    ("CURTISS WRIGHT", "C-46F", "", False, "curtiss_c46", ""),
    ("BOEING", "A75N1", "", False, "stearman", ""),
    ("BOEING", "E75", "", False, "stearman", ""),
    ("NORTH AMERICAN", "AT-6D", "", False, "north_american_t6", ""),
    ("NORTH AMERICAN", "SNJ-5", "", False, "north_american_t6", ""),
    ("NORTH AMERICAN", "P-51D", "", False, "north_american_p51", ""),
    ("NORTH AMERICAN", "NAVION", "", False, "navion", ""),
    ("NORTH AMERICAN", "NA-265-60", "", False, "sabreliner", ""),
    ("YAKOVLEV", "YAK-52", "", False, "yak_nanchang", "yak52"),
    ("AEROSTAR SA", "YAK 52", "", False, "yak_nanchang", "yak52"),
    ("NANCHANG", "CJ-6A", "", False, "yak_nanchang", "cj6"),
    ("AERO VODOCHODY", "L-39C", "", False, "aero_l39", ""),
    ("WACO", "UPF-7", "", False, "waco", ""),
    ("BRITTEN-NORMAN", "BN-2A-26", "", False, "britten_norman_islander", ""),
    ("ROBINSON", "R44", "", False, None, None),
]
