"""Write functions/src/nodeLabels.ts from config/causal_nodes.toml (short labels for the chain viewer).

Run from the repo root after changing node labels:  python tools/gen_node_labels.py
"""
import json
import re
import tomllib
from pathlib import Path

root = Path(__file__).resolve().parent.parent
nodes = tomllib.loads((root / "config/causal_nodes.toml").read_text(encoding="utf-8"))["node"]


def short(label: str) -> str:
    # "Collision with terrain/object (non-CFIT), incl. during takeoff/landing" -> "Collision with terrain/object"
    return re.split(r" \(|, incl\.", label)[0].replace(" / ", "/")


labels = {n["id"]: short(n["label"]) for n in nodes}
labels["outcome.fatal"] = "Fatal"
body = json.dumps(labels, indent=2, ensure_ascii=False)
out = root / "functions/src/nodeLabels.ts"
out.write_text(
    "// Generated by tools/gen_node_labels.py from config/causal_nodes.toml. Do not edit.\n"
    f"export const NODE_LABELS: Record<string, string> = {body};\n",
    encoding="utf-8",
    newline="\n",
)
print(f"{len(labels)} labels -> {out.relative_to(root)}")
